name: .NET Core Desktop

on: 
  push:
    tags:
        - "v*"

env:
  PROJECT_PATH: MabiCookerV3.csproj

jobs:

  deploy:
  
    runs-on: windows-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release -f:net8.0-windows10.0.17763.0

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f:net8.0-windows10.0.17763.0

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{  github.ref_name }}
          files: |
            bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/*.exe
